### PR TITLE
Add geolocation support

### PR DESCRIPTION
**Pull request by fbureau**
Adding geolocation support because without valid GPS Coordinates I am not able to launch the script.

### CODE REVIEW

**Comment by tegob** [comment]
Works fine for me without geolocation…

Tools like this should definitely _NOT_ update the location. This is equivalent to logging into the game using the official Pokémon GO client in a “no GPS signal” mode: you’re still able to retrieve data without any suspicious triggers.

👎 to merging this.

**Comment by fbureau** [comment]
Without geolocation, when I launch the script, I have an error message requesting a geolocation. That's why I have added this.

**Comment by mathiasbynens** [comment]
Please post the full output + error message you‘re getting

**Comment by fbureau** [comment]
I have made a new test without he geolocation and now it working. I do not understand how it change :-/  I spent time to understand why it was not working before finding the problem was coming from geolocation. It seems to longer be an issue. So yes we should drop my request.

**Pull request closed without merging**
