### PR TITLE
Py3 support, save list, location required, help text, syntax fix

### PR DESCRIPTION
**Pull request by u1735067**
Hi, 

based on pull request #33 by @tegob, I corrected the syntax (to many parenthesis), added python3 support, added option to save pokemon list, added some text in the help, and require location for requests (could be suspicious otherwise ?) ; maybe it should be optional but here's a base.

Btw, pgoapi seems to be broken currently ? I only get 

```
  File "[..]\lib\site-packages\pgoapi-1.1.6-py3.5.egg\pgoapi\pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError
```

### CODE REVIEW

**Comment by tegob** [comment]
Could you submit separate patches for each individual feature? That makes it easier to discuss/merge each feature individually. Thanks!

**Comment by tegob** [comment]
> require location for requests (could be suspicious otherwise ?)

There’s nothing suspicious about it — see https://github.com/Boren/PokemonGO-IV-Renamer/pull/27#issuecomment-237569589. Please don’t add location to this tool.

**Comment by u1735067** [comment]
I made position optionnal (and only applied if the 3 coordinates are given).
For the separate patches .. I cannot do that right now. Mainly because I don't know how to do it easily, so if you have any pointer I'll take it ;)
Btw, what would have been the correct way to do it ? Fork, then branch each fonctionnality I add, then merge them to my master ? Because I made those changes on my computer and then wanted to share them.
Btw, should the script (pgoapi especially) be working currently ?

**Comment by tegob** [comment]
@Alex131089 The easiest way to do it is to create a separate branch for each feature. That allows you to send separate pull requests and to update each of them later by just pushing more commits to the appropriate branch.

**Comment by tegob** [comment]
> Btw, should the script (pgoapi especially) be working currently ?

It works fine for me.

**Comment by Boren** [comment]
This project is locked to a older version of pgoapi due to some breaking changes I did not have time to fix.

**Comment by u1735067** [comment]
Done in #45, #46, #47, #48.
@Boren Thanks for the hint, I tried with the latest version ..
I let you close this one ;)

**Pull request closed without merging**
